import { useEffect, useMemo, useState, type FormEvent } from 'react'
import {
  closeDowntime, createDowntime, createPlannedBreak, createWorkShift, getWorkScheduleSummary,
  listDowntimes, listPlannedBreaks, listProductionOrders, listWorkShifts, updatePlannedBreak, updateWorkShift,
} from '../services/api'
import type { DowntimeEvent, PlannedBreak, ProductionLine, ProductionOrder, UserAccount, WorkScheduleSummary, WorkShift } from '../types/domain'
import { formatLocalDateTime } from '../utils/dateTime'

type Props = { lines: ProductionLine[]; user: UserAccount }
type View = 'shifts'|'breaks'|'downtimes'
const emptySummary: WorkScheduleSummary = { active_shifts:0, active_planned_breaks:0, open_downtimes:0 }
const breakLabels: Record<string,string> = { BREAK:'Pausa', MEAL:'Refeição', SETUP:'Setup', OTHER:'Outro' }

function utcIsoFromLocal(value:string) { return value ? new Date(value).toISOString() : '' }
function localNowInput() { const d=new Date(); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); return d.toISOString().slice(0,16) }
function hhmm(value:string) { return value?.slice(0,5) ?? '—' }
function minutesLabel(value:number) { const h=Math.floor(value/60), m=value%60; return h ? `${h}h${String(m).padStart(2,'0')}` : `${m} min` }

export function WorkSchedulePanel({ lines, user }:Props) {
  const isAdmin=user.role==='ADMIN'; const canOperate=isAdmin||user.role==='SUPERVISOR'
  const [view,setView]=useState<View>('shifts'); const [formOpen,setFormOpen]=useState(false)
  const [summary,setSummary]=useState<WorkScheduleSummary>(emptySummary); const [error,setError]=useState(''); const [success,setSuccess]=useState('')
  const [shifts,setShifts]=useState<WorkShift[]>([]); const [shiftTotal,setShiftTotal]=useState(0); const [shiftPage,setShiftPage]=useState(1); const [shiftPages,setShiftPages]=useState(1)
  const [breaks,setBreaks]=useState<PlannedBreak[]>([]); const [breakTotal,setBreakTotal]=useState(0); const [breakPage,setBreakPage]=useState(1); const [breakPages,setBreakPages]=useState(1)
  const [downtimes,setDowntimes]=useState<DowntimeEvent[]>([]); const [downTotal,setDownTotal]=useState(0); const [downPage,setDownPage]=useState(1); const [downPages,setDownPages]=useState(1)
  const [orders,setOrders]=useState<ProductionOrder[]>([])
  const [allActiveShifts,setAllActiveShifts]=useState<WorkShift[]>([])
  const [editingShift,setEditingShift]=useState<WorkShift|null>(null)
  const [editingBreak,setEditingBreak]=useState<PlannedBreak|null>(null)
  const [shiftForm,setShiftForm]=useState({line_id:'',code:'T1',name:'1º Turno',start_time:'06:00',end_time:'14:00'})
  const [breakForm,setBreakForm]=useState({shift_id:'',name:'Intervalo',break_type:'BREAK',start_time:'09:00',end_time:'09:15'})
  const [downForm,setDownForm]=useState({line_id:'',production_order_id:'',shift_id:'',category:'UNPLANNED',reason:'',started_at:localNowInput(),ended_at:'',notes:''})

  const activeShifts=useMemo(()=>allActiveShifts,[allActiveShifts])
  async function loadSummary(){ try{setSummary(await getWorkScheduleSummary())}catch(e){setError((e as Error).message)} }
  async function loadShifts(page=shiftPage){ try{const d=await listWorkShifts({page,page_size:5});setShifts(d.items);setShiftTotal(d.total);setShiftPage(d.page);setShiftPages(d.total_pages)}catch(e){setError((e as Error).message)} }
  async function loadBreaks(page=breakPage){ try{const d=await listPlannedBreaks({page,page_size:5});setBreaks(d.items);setBreakTotal(d.total);setBreakPage(d.page);setBreakPages(d.total_pages)}catch(e){setError((e as Error).message)} }
  async function loadDown(page=downPage){ try{const d=await listDowntimes({page,page_size:5});setDowntimes(d.items);setDownTotal(d.total);setDownPage(d.page);setDownPages(d.total_pages)}catch(e){setError((e as Error).message)} }
  async function refreshAll(){ await Promise.all([loadSummary(),loadShifts(1),loadBreaks(1),loadDown(1)]); try{const shiftsData=await listWorkShifts({page:1,page_size:50,active:true});setAllActiveShifts(shiftsData.items)}catch{} try{const d=await listProductionOrders({page:1,page_size:50});setOrders(d.items.filter(x=>['ACTIVE','PAUSED','OPEN'].includes(x.status)))}catch{} }
  useEffect(()=>{refreshAll()},[])

  function choose(v:View){setView(v);setFormOpen(false);setEditingShift(null);setEditingBreak(null);setError('');setSuccess('')}
  function editShift(item:WorkShift){setEditingShift(item);setShiftForm({line_id:String(item.line_id),code:item.code,name:item.name,start_time:hhmm(item.start_time),end_time:hhmm(item.end_time)});setFormOpen(true)}
  function editBreak(item:PlannedBreak){setEditingBreak(item);setBreakForm({shift_id:String(item.shift_id),name:item.name,break_type:item.break_type,start_time:hhmm(item.start_time),end_time:hhmm(item.end_time)});setFormOpen(true)}
  async function saveShift(e:FormEvent){e.preventDefault();try{if(editingShift) await updateWorkShift(editingShift.id,{code:shiftForm.code.trim(),name:shiftForm.name.trim(),start_time:shiftForm.start_time,end_time:shiftForm.end_time});else await createWorkShift({line_id:Number(shiftForm.line_id),code:shiftForm.code.trim(),name:shiftForm.name.trim(),start_time:shiftForm.start_time,end_time:shiftForm.end_time});setSuccess(editingShift?'Turno atualizado.':'Turno cadastrado.');setEditingShift(null);setFormOpen(false);await refreshAll()}catch(e){setError((e as Error).message)}}
  async function saveBreak(e:FormEvent){e.preventDefault();try{if(editingBreak) await updatePlannedBreak(editingBreak.id,{name:breakForm.name.trim(),break_type:breakForm.break_type,start_time:breakForm.start_time,end_time:breakForm.end_time});else await createPlannedBreak({shift_id:Number(breakForm.shift_id),name:breakForm.name.trim(),break_type:breakForm.break_type,start_time:breakForm.start_time,end_time:breakForm.end_time});setSuccess(editingBreak?'Pausa atualizada.':'Pausa planejada cadastrada.');setEditingBreak(null);setFormOpen(false);await refreshAll()}catch(e){setError((e as Error).message)}}
  async function saveDowntime(e:FormEvent){e.preventDefault();try{await createDowntime({line_id:Number(downForm.line_id),production_order_id:downForm.production_order_id?Number(downForm.production_order_id):undefined,shift_id:downForm.shift_id?Number(downForm.shift_id):undefined,category:downForm.category,reason:downForm.reason.trim(),started_at:utcIsoFromLocal(downForm.started_at),ended_at:downForm.ended_at?utcIsoFromLocal(downForm.ended_at):undefined,notes:downForm.notes||undefined});setSuccess('Parada registrada.');setFormOpen(false);await refreshAll()}catch(e){setError((e as Error).message)}}
  async function toggleShift(item:WorkShift){try{await updateWorkShift(item.id,{active:!item.active});await refreshAll()}catch(e){setError((e as Error).message)}}
  async function toggleBreak(item:PlannedBreak){try{await updatePlannedBreak(item.id,{active:!item.active});await refreshAll()}catch(e){setError((e as Error).message)}}
  async function finishDown(item:DowntimeEvent){try{await closeDowntime(item.id,new Date().toISOString());setSuccess('Parada encerrada.');await refreshAll()}catch(e){setError((e as Error).message)}}

  return <section className="panel work-schedule-panel">
    <div className="panel-heading"><div><p className="eyebrow">GESTÃO DO TEMPO PRODUTIVO</p><h2>Jornada, turnos, pausas e paradas</h2></div><span className="badge success">base para eficiência / OEE</span></div>
    {error&&<div className="message error">{error}</div>}{success&&<div className="message success">{success}</div>}
    <div className="schedule-summary"><div><span>Turnos ativos</span><strong>{summary.active_shifts}</strong></div><div><span>Pausas planejadas</span><strong>{summary.active_planned_breaks}</strong></div><div className={summary.open_downtimes?'warning':''}><span>Paradas abertas</span><strong>{summary.open_downtimes}</strong></div></div>
    <div className="schedule-tabs"><button className={view==='shifts'?'active':''} onClick={()=>choose('shifts')}>Turnos <b>{shiftTotal}</b></button><button className={view==='breaks'?'active':''} onClick={()=>choose('breaks')}>Pausas <b>{breakTotal}</b></button><button className={view==='downtimes'?'active':''} onClick={()=>choose('downtimes')}>Paradas <b>{downTotal}</b></button></div>

    <div className="schedule-toolbar"><div><strong>{view==='shifts'?'Jornadas de produção':view==='breaks'?'Pausas planejadas':'Registro de paradas'}</strong><small>{view==='shifts'?'Configure horários por linha. Turnos podem atravessar meia-noite.':view==='breaks'?'Intervalos descontáveis do tempo planejado, vinculados a um turno.':'Registre parada planejada ou não planejada; OEE ainda não é calculado.'}</small></div>{((view!=='downtimes'&&isAdmin)||(view==='downtimes'&&canOperate))&&<button className="secondary small" onClick={()=>setFormOpen(v=>!v)}>☰ {formOpen?'Fechar':'Novo registro'}</button>}</div>

    {formOpen&&view==='shifts'&&isAdmin&&<form className="schedule-form" onSubmit={saveShift}><div className="field"><label>Linha</label><select required disabled={!!editingShift} value={shiftForm.line_id} onChange={e=>setShiftForm(v=>({...v,line_id:e.target.value}))}><option value="">Selecione</option>{lines.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></div><div className="field"><label>Código</label><input required value={shiftForm.code} onChange={e=>setShiftForm(v=>({...v,code:e.target.value}))}/></div><div className="field"><label>Nome</label><input required value={shiftForm.name} onChange={e=>setShiftForm(v=>({...v,name:e.target.value}))}/></div><div className="field"><label>Início</label><input type="time" required value={shiftForm.start_time} onChange={e=>setShiftForm(v=>({...v,start_time:e.target.value}))}/></div><div className="field"><label>Fim</label><input type="time" required value={shiftForm.end_time} onChange={e=>setShiftForm(v=>({...v,end_time:e.target.value}))}/></div><button className="primary" type="submit">{editingShift?'Salvar turno':'Cadastrar turno'}</button></form>}
    {formOpen&&view==='breaks'&&isAdmin&&<form className="schedule-form" onSubmit={saveBreak}><div className="field"><label>Turno</label><select required disabled={!!editingBreak} value={breakForm.shift_id} onChange={e=>setBreakForm(v=>({...v,shift_id:e.target.value}))}><option value="">Selecione</option>{activeShifts.map(x=><option key={x.id} value={x.id}>{x.line_code} · {x.code} · {x.name}</option>)}</select></div><div className="field"><label>Nome</label><input required value={breakForm.name} onChange={e=>setBreakForm(v=>({...v,name:e.target.value}))}/></div><div className="field"><label>Tipo</label><select value={breakForm.break_type} onChange={e=>setBreakForm(v=>({...v,break_type:e.target.value}))}><option value="BREAK">Pausa</option><option value="MEAL">Refeição</option><option value="SETUP">Setup planejado</option><option value="OTHER">Outro</option></select></div><div className="field"><label>Início</label><input type="time" required value={breakForm.start_time} onChange={e=>setBreakForm(v=>({...v,start_time:e.target.value}))}/></div><div className="field"><label>Fim</label><input type="time" required value={breakForm.end_time} onChange={e=>setBreakForm(v=>({...v,end_time:e.target.value}))}/></div><button className="primary" type="submit">{editingBreak?'Salvar pausa':'Cadastrar pausa'}</button></form>}
    {formOpen&&view==='downtimes'&&canOperate&&<form className="schedule-form downtime-form" onSubmit={saveDowntime}><div className="field"><label>Linha</label><select required value={downForm.line_id} onChange={e=>setDownForm(v=>({...v,line_id:e.target.value,shift_id:'',production_order_id:''}))}><option value="">Selecione</option>{lines.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></div><div className="field"><label>Turno (opcional)</label><select value={downForm.shift_id} onChange={e=>setDownForm(v=>({...v,shift_id:e.target.value}))}><option value="">Não informado</option>{activeShifts.filter(x=>!downForm.line_id||x.line_id===Number(downForm.line_id)).map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></div><div className="field"><label>OP (opcional)</label><select value={downForm.production_order_id} onChange={e=>setDownForm(v=>({...v,production_order_id:e.target.value}))}><option value="">Não informada</option>{orders.filter(x=>!downForm.line_id||!x.line_id||x.line_id===Number(downForm.line_id)).map(x=><option key={x.id} value={x.id}>{x.order_number} · {x.status}</option>)}</select></div><div className="field"><label>Categoria</label><select value={downForm.category} onChange={e=>setDownForm(v=>({...v,category:e.target.value}))}><option value="UNPLANNED">Não planejada</option><option value="PLANNED">Planejada</option></select></div><div className="field"><label>Motivo</label><input required value={downForm.reason} onChange={e=>setDownForm(v=>({...v,reason:e.target.value}))} placeholder="Ex.: falta de material"/></div><div className="field"><label>Início</label><input type="datetime-local" required value={downForm.started_at} onChange={e=>setDownForm(v=>({...v,started_at:e.target.value}))}/></div><div className="field"><label>Fim (opcional)</label><input type="datetime-local" value={downForm.ended_at} onChange={e=>setDownForm(v=>({...v,ended_at:e.target.value}))}/></div><div className="field notes"><label>Observação</label><input value={downForm.notes} onChange={e=>setDownForm(v=>({...v,notes:e.target.value}))}/></div><button className="primary" type="submit">Registrar parada</button></form>}

    <div className="table-wrap schedule-table-wrap"><table><thead>{view==='shifts'?<tr><th>LINHA</th><th>TURNO</th><th>HORÁRIO</th><th>JORNADA</th><th>PAUSAS</th><th>ÚTIL PLANEJADO</th><th>STATUS</th><th>AÇÃO</th></tr>:view==='breaks'?<tr><th>LINHA</th><th>TURNO</th><th>PAUSA</th><th>TIPO</th><th>HORÁRIO</th><th>DURAÇÃO</th><th>STATUS</th><th>AÇÃO</th></tr>:<tr><th>LINHA</th><th>INÍCIO</th><th>FIM</th><th>TIPO</th><th>MOTIVO</th><th>OP/TURNO</th><th>DURAÇÃO</th><th>AÇÃO</th></tr>}</thead><tbody>
      {view==='shifts'&&shifts.map(x=><tr key={x.id}><td>{x.line_code}</td><td><strong>{x.code}</strong><small>{x.name}</small></td><td>{hhmm(x.start_time)}–{hhmm(x.end_time)}{x.crosses_midnight&&<small>vira o dia</small>}</td><td>{minutesLabel(x.planned_minutes)}</td><td>{minutesLabel(x.planned_break_minutes)}</td><td><strong>{minutesLabel(x.net_planned_minutes)}</strong></td><td><span className={`badge ${x.active?'success':''}`}>{x.active?'ATIVO':'INATIVO'}</span></td><td>{isAdmin&&<div className="row-actions"><button className="secondary tiny" onClick={()=>editShift(x)}>Editar</button><button className="secondary tiny" onClick={()=>toggleShift(x)}>{x.active?'Desativar':'Ativar'}</button></div>}</td></tr>)}
      {view==='breaks'&&breaks.map(x=><tr key={x.id}><td>{x.line_code}</td><td>{x.shift_code}</td><td><strong>{x.name}</strong></td><td>{breakLabels[x.break_type]}</td><td>{hhmm(x.start_time)}–{hhmm(x.end_time)}</td><td>{x.duration_minutes} min</td><td><span className={`badge ${x.active?'success':''}`}>{x.active?'ATIVA':'INATIVA'}</span></td><td>{isAdmin&&<div className="row-actions"><button className="secondary tiny" onClick={()=>editBreak(x)}>Editar</button><button className="secondary tiny" onClick={()=>toggleBreak(x)}>{x.active?'Desativar':'Ativar'}</button></div>}</td></tr>)}
      {view==='downtimes'&&downtimes.map(x=><tr key={x.id}><td>{x.line_code}</td><td>{formatLocalDateTime(x.started_at)}</td><td>{x.ended_at?formatLocalDateTime(x.ended_at):<span className="badge warning">EM ABERTO</span>}</td><td><span className={`badge ${x.category==='PLANNED'?'':'warning'}`}>{x.category==='PLANNED'?'PLANEJADA':'NÃO PLANEJADA'}</span></td><td><strong>{x.reason}</strong><small>{x.notes}</small></td><td>{x.production_order??'—'}<small>{x.shift_code??'sem turno'}</small></td><td>{x.duration_minutes} min</td><td>{x.status==='OPEN'&&canOperate&&<button className="primary tiny" onClick={()=>finishDown(x)}>Encerrar agora</button>}</td></tr>)}
      {((view==='shifts'&&!shifts.length)||(view==='breaks'&&!breaks.length)||(view==='downtimes'&&!downtimes.length))&&<tr><td colSpan={8}>Nenhum registro cadastrado.</td></tr>}
    </tbody></table></div>
    <div className="pagination-row"><span>{view==='shifts'?shiftTotal:view==='breaks'?breakTotal:downTotal} registro(s)</span><div><button className="secondary small" disabled={(view==='shifts'?shiftPage:view==='breaks'?breakPage:downPage)<=1} onClick={()=>view==='shifts'?loadShifts(shiftPage-1):view==='breaks'?loadBreaks(breakPage-1):loadDown(downPage-1)}>Anterior</button><strong>Página {view==='shifts'?shiftPage:view==='breaks'?breakPage:downPage} de {view==='shifts'?shiftPages:view==='breaks'?breakPages:downPages}</strong><button className="secondary small" disabled={(view==='shifts'?shiftPage:view==='breaks'?breakPage:downPage)>=(view==='shifts'?shiftPages:view==='breaks'?breakPages:downPages)} onClick={()=>view==='shifts'?loadShifts(shiftPage+1):view==='breaks'?loadBreaks(breakPage+1):loadDown(downPage+1)}>Próxima</button></div></div>
  </section>
}
